export const languages: string[] = [
  "🇺🇸 US English",
  "🇩🇪 German",
  "🇮🇹 Italian",
  "🇫🇷 French",
  "🇪🇸 Spanish",
  "🇵🇹 Portuguese",
  "🇳🇱 Dutch",
  "🇸🇪 Swedish",
  "🇵🇱 Polish",
  "🇭🇷 Croatian",
  "🇩🇰 Danish",
  "🇳🇴 Norwegian",
  "🇫🇮 Finnish",
  "🇧🇬 Bulgarian",
  "🇭🇺 Hungarian",
  "🇨🇿 Czech",
  "🇸🇮 Slovenian",
  "🇸🇰 Slovak",
  "🇱🇹 Lithuanian",
  "🇪🇪 Estonian",
  "🇷🇴 Romanian",
  "🇦🇱 Albanian",
  "🇦🇩 Catalan",
  "🇬🇧 British English",
  "🇧🇷 Brazilian Portuguese",
  "🇨🇦 Canadian French",
  "🇦🇷 Argentine Spanish",
  "🇲🇽 Mexican Spanish",
  "🇻🇪 Venezuelan Spanish",
  "🇨🇬 Colombian Spanish",
  "🇨🇺 Cuban Spanish",
  "🇨🇱 Chilean Spanish",
];
