import { Language } from "@/lib/store";

export const LANGUAGES: Language[] = [
  {
    code: "en-US",
    name: "US English",
    display: "🇺🇸 US English",
    locale: "en-US",
  },
  {
    code: "en-GB",
    name: "British English",
    display: "🇬🇧 British English",
    locale: "en-GB",
  },
  { code: "de", name: "German", display: "🇩🇪 German", locale: "de" },
  { code: "it", name: "Italian", display: "🇮🇹 Italian", locale: "it" },
  { code: "fr", name: "French", display: "🇫🇷 French", locale: "fr" },
  { code: "es", name: "Spanish", display: "🇪🇸 Spanish", locale: "es" },
  { code: "pt", name: "Portuguese", display: "🇵🇹 Portuguese", locale: "pt" },
  { code: "nl", name: "Dutch", display: "🇳🇱 Dutch", locale: "nl" },
  { code: "sv", name: "Swedish", display: "🇸🇪 Swedish", locale: "sv" },
  { code: "pl", name: "Polish", display: "🇵🇱 Polish", locale: "pl" },
  { code: "hr", name: "Croatian", display: "🇭🇷 Croatian", locale: "hr" },
  { code: "da", name: "Danish", display: "🇩🇰 Danish", locale: "da" },
  { code: "no", name: "Norwegian", display: "🇳🇴 Norwegian", locale: "no" },
  { code: "fi", name: "Finnish", display: "🇫🇮 Finnish", locale: "fi" },
  { code: "bg", name: "Bulgarian", display: "🇧🇬 Bulgarian", locale: "bg" },
  { code: "hu", name: "Hungarian", display: "🇭🇺 Hungarian", locale: "hu" },
  { code: "cs", name: "Czech", display: "🇨🇿 Czech", locale: "cs" },
  { code: "sl", name: "Slovenian", display: "🇸🇮 Slovenian", locale: "sl" },
  { code: "sk", name: "Slovak", display: "🇸🇰 Slovak", locale: "sk" },
  { code: "lt", name: "Lithuanian", display: "🇱🇹 Lithuanian", locale: "lt" },
  { code: "et", name: "Estonian", display: "🇪🇪 Estonian", locale: "et" },
  { code: "ro", name: "Romanian", display: "🇷🇴 Romanian", locale: "ro" },
  { code: "sq", name: "Albanian", display: "🇦🇱 Albanian", locale: "sq" },
  { code: "ca", name: "Catalan", display: "🇦🇩 Catalan", locale: "ca" },
  {
    code: "pt-BR",
    name: "Brazilian Portuguese",
    display: "🇧🇷 Brazilian Portuguese",
    locale: "pt-BR",
  },
  {
    code: "fr-CA",
    name: "Canadian French",
    display: "🇨🇦 Canadian French",
    locale: "fr-CA",
  },
  {
    code: "es-AR",
    name: "Argentine Spanish",
    display: "🇦🇷 Argentine Spanish",
    locale: "es-AR",
  },
  {
    code: "es-MX",
    name: "Mexican Spanish",
    display: "🇲🇽 Mexican Spanish",
    locale: "es-MX",
  },
  {
    code: "es-VE",
    name: "Venezuelan Spanish",
    display: "🇻🇪 Venezuelan Spanish",
    locale: "es-VE",
  },
  {
    code: "es-CO",
    name: "Colombian Spanish",
    display: "🇨🇴 Colombian Spanish",
    locale: "es-CO",
  },
  {
    code: "es-CU",
    name: "Cuban Spanish",
    display: "🇨🇺 Cuban Spanish",
    locale: "es-CU",
  },
  {
    code: "es-CL",
    name: "Chilean Spanish",
    display: "🇨🇱 Chilean Spanish",
    locale: "es-CL",
  },
];
